Word Embedding Techniques using embedding layers in keras

In [ ]:
!pip install tensorflow

In [ ]:
!pip install keras


In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
### Vocubolary size
voc_size=10000

One Hot Representation

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in sent]

In [ ]:
print(onehot_repr)

[[2373, 8004, 666, 8971], [2373, 8004, 666, 6700], [2373, 7296, 666, 3109], [4409, 6630, 8833, 9469, 3200], [4409, 6630, 8833, 9469, 5003], [7811, 2373, 382, 666, 9276], [2104, 2829, 5637, 9469]]


Word Embedding Representation

In [ ]:
from tensorflow.keras.layers import Embedding

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np


In [ ]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2373 8004  666 8971]
 [   0    0    0    0 2373 8004  666 6700]
 [   0    0    0    0 2373 7296  666 3109]
 [   0    0    0 4409 6630 8833 9469 3200]
 [   0    0    0 4409 6630 8833 9469 5003]
 [   0    0    0 7811 2373  382  666 9276]
 [   0    0    0    0 2104 2829 5637 9469]]


In [ ]:
dim=10

In [ ]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam', 'mse')

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 124ms/step
[[[ 0.04343951 -0.04441161 -0.00095301  0.01611929 -0.02815726
    0.01493584 -0.04762666 -0.00304216 -0.04135424  0.0077909 ]
  [ 0.04343951 -0.04441161 -0.00095301  0.01611929 -0.02815726
    0.01493584 -0.04762666 -0.00304216 -0.04135424  0.0077909 ]
  [ 0.04343951 -0.04441161 -0.00095301  0.01611929 -0.02815726
    0.01493584 -0.04762666 -0.00304216 -0.04135424  0.0077909 ]
  [ 0.04343951 -0.04441161 -0.00095301  0.01611929 -0.02815726
    0.01493584 -0.04762666 -0.00304216 -0.04135424  0.0077909 ]
  [-0.040658    0.03962423 -0.02337171  0.03919644 -0.00481651
    0.03091986  0.00574694  0.03425269  0.02810467 -0.04578168]
  [-0.01433998 -0.00923745  0.02676913  0.04994356  0.0237918
    0.012671    0.00460069  0.02211826  0.02205053 -0.01058496]
  [-0.01026317  0.01805801  0.00847073 -0.02628641  0.00089699
   -0.00690592 -0.01349676 -0.04024022 -0.0476905   0.00981789]
  [ 0.02906803 -0.01190741  0.02638758  0.03803441 -0.00522

In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0, 2373, 8004,  666, 8971], dtype=int32)

In [ ]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 23ms/step
[[ 0.04343951 -0.04441161 -0.00095301  0.01611929 -0.02815726  0.01493584
  -0.04762666 -0.00304216 -0.04135424  0.0077909 ]
 [ 0.04343951 -0.04441161 -0.00095301  0.01611929 -0.02815726  0.01493584
  -0.04762666 -0.00304216 -0.04135424  0.0077909 ]
 [ 0.04343951 -0.04441161 -0.00095301  0.01611929 -0.02815726  0.01493584
  -0.04762666 -0.00304216 -0.04135424  0.0077909 ]
 [ 0.04343951 -0.04441161 -0.00095301  0.01611929 -0.02815726  0.01493584
  -0.04762666 -0.00304216 -0.04135424  0.0077909 ]
 [-0.040658    0.03962423 -0.02337171  0.03919644 -0.00481651  0.03091986
   0.00574694  0.03425269  0.02810467 -0.04578168]
 [-0.01433998 -0.00923745  0.02676913  0.04994356  0.0237918   0.012671
   0.00460069  0.02211826  0.02205053 -0.01058496]
 [-0.01026317  0.01805801  0.00847073 -0.02628641  0.00089699 -0.00690592
  -0.01349676 -0.04024022 -0.0476905   0.00981789]
 [ 0.02906803 -0.01190741  0.02638758  0.03803441 -0.00522809  0.04887475
 